import type { Metadata } from "next";
import "./globals.css";
import { NavbarComponent } from "@/components/navbar";
import { Gothic_A1 } from 'next/font/google';
import Footer from "@/components/Features/Footer/Footer";
import { companyLinks, CommunityLinks} from "@/lib/data";
import PageLoader from "./progressBar";

const gothicA1 = Gothic_A1({
  subsets:['latin'],
  weight:['200','300','400','500','600','700','800', '900'],
  display:'swap',
 })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gothicA1.className} overflow-x-hidden  antialiased`}>
        <PageLoader>
        <NavbarComponent />
        {children}
        <Footer companyLinks={companyLinks} CommunityLinks={CommunityLinks}  />
        </PageLoader>
      </body>
    </html>
  );
}
