import testImage from "@/assets/testimage.webp"
import testImageTwo from "@/assets/testImageTwo.webp"
const text =
  "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque est quia, ducimus totam nisi tempore corporis amet expedita? Rerum, sint, repellat temporibus fugiat minima odio sapiente officia officiis voluptas neque quae deserunt soluta, velit molestias suscipit labore dolorum accusamus consequuntur! Tenetur magnam nobis quae ut, dolore dolorum sint repellat. Odio deserunt, distinctio et impedit accusantium odit nam praesentium facilis perspiciatis! Soluta, officia asperiores veritatis debitis sequi voluptatum deserunt ullam omnis dolor fuga quo libero obcaecati voluptas labore ea at excepturi animi a sit? Est atque explicabo non asperiores eligendi, quam numquam distinctio odio quaerat ad neque natus in tempora eos!";

  export const categories =[
    {
        title:'Digital marketing',
        url:'',
    },
    {
        title:'Seo',
        url:'',
    },
    {
        title:'Content management',
        url:'',
    },
    {
        title:'Tips',
        url:'',
    },
  ] 

  export const blogs = [
  {
    id: "1",
    details: text,
    coverPhoto:testImage,
    category: "Seo",
    tags: "popular",
    title: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    authour: "Jane Smith",
    readTIme: "2",
    date: "May 15, 2021",
  },
  {
    id: "2",
    details: text,
    coverPhoto:testImageTwo,
    category: "Seo",
    tags: "popular",
    title: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    authour: "Jane Smith",
    readTIme: "2",
    date: "May 15, 2021",
  },
  {
    id: "3",
    details: text,
    coverPhoto:testImage,
    category: "Seo",
    tags: "popular",
    title: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    authour: "Jane Smith",
    readTIme: "2",
    date: "May 15, 2021",
  },
  {
    id: "4",
    details: text,
    coverPhoto:testImage,
    category: "Seo",
    tags: "popular",
    title: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    authour: "Jane Smith",
    readTIme: "2",
    date: "May 15, 2021",
  },
  {
    id: "5",
    details: text,
    coverPhoto:testImage,
    category: "Seo",
    tags: "popular",
    title: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    authour: "Jane Smith",
    readTIme: "2",
    date: "May 15, 2021",
  },
  {
    id: "6",
    details: text,
    coverPhoto:testImage,
    category: "Seo",
    tags: "popular",
    title: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    authour: "Jane Smith",
    readTIme: "2",
    date: "May 15, 2021",
  },
  {
    id: "7",
    details: text,
    coverPhoto:testImage,
    category: "digital_marketing",
    tags: "popular",
    title: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    authour: "Jane Smith",
    readTIme: "2",
    date: "May 15, 2021",
  },
  {
    id: "8",
    details: text,
    coverPhoto:testImage,
    category: "digital_marketing",
    tags: "popular",
    title: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    authour: "Jane Smith",
    readTIme: "2",
    date: "May 15, 2021",
  },
  {
    id: "9",
    details: text,
    coverPhoto:testImage,
    category: "digital_marketing",
    tags: "popular",
    title: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    authour: "Jane Smith",
    readTIme: "2",
    date: "May 15, 2021",
  },
  {
    id: "10",
    details: text,
    coverPhoto:testImage,
    category: "digital_marketing",
    tags: "popular",
    title: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    authour: "Jane Smith",
    readTIme: "2",
    date: "May 15, 2021",
  },
  {
    id: "11",
    details: text,
    coverPhoto:testImage,
    category: "digital_marketing",
    tags: "popular",
    title: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    authour: "Jane Smith",
    readTIme: "2",
    date: "May 15, 2021",
  },
  {
    id: "12",
    details: text,
    coverPhoto:testImage,
    category: "digital_marketing",
    tags: "popular",
    title: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    authour: "Jane Smith",
    readTIme: "2",
    date: "May 15, 2021",
  },
];
